//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdmenStoreDAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdmenStore
    {
        public int PId { get; set; }
        public string PName { get; set; }
        public string PType { get; set; }
        public int PQuantity { get; set; }
        public double PCost { get; set; }
        public double PPrice { get; set; }
    }
}
