//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpDAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpRegistration
    {
        public int EmpId { get; set; }
        public string EmpName { get; set; }
        public string EmpCnic { get; set; }
        public string EmpEmail { get; set; }
        public string EmpPhone { get; set; }
        public string EmpPassword { get; set; }
        public string EmpAddress { get; set; }
    }
}
