//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderDAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderId { get; set; }
        public string VehicleType { get; set; }
        public string VehicleNumber { get; set; }
        public string ServiceType { get; set; }
        public decimal Latitude { get; set; }
        public decimal Longitude { get; set; }
        public string Discreption { get; set; }
        public int CustId { get; set; }
        public int FoId { get; set; }
    }
}
