//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrenchiseDAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FrenchiseRegistration
    {
        public int FoId { get; set; }
        public string FoName { get; set; }
        public string FoCnic { get; set; }
        public string FoEmail { get; set; }
        public string FoPhone { get; set; }
        public string FoPassword { get; set; }
        public string FoCity { get; set; }
        public string FoAddress { get; set; }
    }
}
