//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdmenDAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdmenRegistration
    {
        public int AdId { get; set; }
        public string AdName { get; set; }
        public string AdCnic { get; set; }
        public string AdEmail { get; set; }
        public string AdPhone { get; set; }
        public string AdPassword { get; set; }
        public string AdAddress { get; set; }
    }
}
